### ISSUE TITLE
Deprecation of API v.1

### ISSUE THREAD

**Issue by danielsz** [pavpanchekha/dropbox.el#2]
Sadly, the API used by `dropbox.el` has been deprecated on September 28th 2017. 
Dropbox offers a migration guide, but someone will have to do the work. 
I'm leaving this note here as a warning to prospective users, and also to solicit a response as to whether the author has plans to port this otherwise excellent mode to API v2. Thank you.

**Comment by pavpanchekha** [comment]
I wrote this package a few years ago at a Dropbox hackathon; I basically never use it anymore.

@danielsz, do you have any experience with the v1.1→v2 migration? How difficult is it? If it is mechanical, I may try to find time to do the work, though I will need users. If it is very complex (did the OAuth flow change?) then I'm unlikely to do it.

**Comment by danielsz** [comment]
Hi Pavel, 

Thanks for the reply!
To me, the difference that stands out between OAuth 1 and OAuth 2 is that the crypto dance you had to do with OAuth 1 is gone. OAuth had a terrible usability problem. While rethinking the protocol, the designers reasoned that the security guarantees of the channel over which the authentication is taking place (https) could and should be leveraged. So they removed the cryptographic signing that clients needed to perform. But then they also worked on flows and user experience. The spec defines a number of grant types adapted to varying use cases. Dropbox has [support](https://blogs.dropbox.com/developers/2013/07/using-oauth-2-0-with-the-core-api/) for Authorization Code Grant (app with server-side component) and Implicit grant (client-side app).
OAuth 1 resembles the Authorization Code Grant, but `dropbox.el` can leverage the Implicit grant. Instead of the authorization server returning an authorization code which is exchanged for an access token, the authorization server returns an access token.

> Note that for certain apps, such as command line and desktop apps, it's not possible for a web browser to redirect back to your app. In these cases, your app does not need to include a redirect_uri parameter. Dropbox will present the user with an authorization code that they will need to copy and paste into your app, at which point your app can exchange it for a reusable access token.
> Excerpt from [Dropbox's OAuth guide](https://www.dropbox.com/developers/reference/oauth-guide). 


Oh, and I'll be more than happy to serve as your beta user.

I hope this helps. 
Daniel

**Comment by pavpanchekha** [comment]
I've started looking into this. It looks like there is an `oauth2` package for Emacs that implements the OAuth2 protocol, and it's pretty nice to use (I like this blog post: http://blog.jenkster.com/2013/10/an-oauth2-in-emacs-example.html). In particular, the `oauth2` package has a very similar API to the `oauth` package that `dropbox.el` uses right now.

In `dropbox.el`, I only need to change `dropbox-get`, `dropbox-post`, `dropbox-authenticate`, and `oauth-curl-retrieve`, which seems doable. I need some time to learn how OAuth works, and it seems like the setup steps (creating a private application and saving the tokens) will be similar.

The rest of the code will need random changes: the endpoints changed names and the API has a different format. Most of these changes aren't too large, because Dropbox hasn't changed much, luckily.

I think this would be a few days of work. @danielsz are you still willing to beta-test?

**Comment by danielsz** [comment]
That sounds like a great plan, @pavpanchekha. I'm in, absolutely.

**Comment by railsnoob** [comment]
Guys I can offer both of you a beer if you can fix this? :)

**Comment by pavpanchekha** [comment]
Sorry @railsnoob, it's a question of finding the time. :(

**Comment by danielsz** [comment]
I've switched to another solution. I'm using Syncthing. 

https://chaidarun.com/dropbox-syncthing

Highly recommended.

**Comment by railsnoob** [comment]
I have my reasons, but I want to be able to reach my Dropbox files with no sync.

**Comment by pavpanchekha** [comment]
This has now been partially addressed, thanks to @maxsatula! You will likely need to reconfigure the package (APIv2 has a new authentication system) but the basics work.
